export type Difficulty = 1 | 2 | 3;

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  1: "Easy",
  2: "Medium",
  3: "Hard",
};

export const DIFFICULTY_LOCATIONS: Record<Difficulty, string[]> = {
  1: [
    "Eiffel Tower",
    "Colosseum",
    "Statue of Liberty",
    "Big Ben",
    "Sydney Opera House",
    "Golden Gate Bridge",
    "Christ the Redeemer (statue)",
    "Taj Mahal",
    "Great Wall of China",
    "Burj Khalifa",
    "Leaning Tower of Pisa",
    "Machu Picchu",
    "Sagrada Família",
    "Mount Fuji",
    "Tower Bridge",
  ],
  2: [
    "Neuschwanstein Castle",
    "Angkor Wat",
    "Petra",
    "Hagia Sophia",
    "Charles Bridge",
    "Acropolis of Athens",
    "Blue Mosque",
    "Brandenburg Gate",
    "Alhambra",
    "Edinburgh Castle",
    "Forbidden City",
    "Notre-Dame de Paris",
    "Chichén Itzá",
    "Stonehenge",
    "Santorini",
  ],
  3: [
    "Bagan",
    "Meteora",
    "Moai",
    "Gobekli Tepe",
    "Sigiriya",
    "Borobudur",
    "Lalibela",
    "Persepolis",
    "Great Zimbabwe",
    "Hampi",
    "Tikal",
    "Newgrange",
    "Mont-Saint-Michel",
    "Ajanta Caves",
    "Cappadocia",
  ],
};
