export type Difficulty = 1 | 2 | 3;

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  1: "Easy",
  2: "Medium",
  3: "Hard",
};

export const DIFFICULTY_LOCATIONS: Record<Difficulty, string[]> = {
  1: [
    "Eiffel Tower",
    "Colosseum",
    "Statue of Liberty",
    "Big Ben",
    "Sydney Opera House",
    "Golden Gate Bridge",
    "Christ the Redeemer (statue)",
    "Taj Mahal",
    "Great Wall of China",
    "Burj Khalifa",
    "Leaning Tower of Pisa",
    "Machu Picchu",
    "Sagrada Família",
    "Mount Fuji",
    "Tower Bridge",
    "Pyramids of Giza",
    "Parthenon",
    "St. Peter's Basilica",
    "Niagara Falls",
    "Mount Rushmore",
    "Palace of Versailles",
    "Buckingham Palace",
    "Empire State Building",
    "Acropolis of Athens",
    "Hagia Sophia",
    "Arc de Triomphe",
    "Angkor Wat",
    "Kremlin",
    "Opera Garnier",
    "Trevi Fountain",
  ],
  2: [
    "Neuschwanstein Castle",
    "Petra",
    "Charles Bridge",
    "Blue Mosque",
    "Brandenburg Gate",
    "Alhambra",
    "Edinburgh Castle",
    "Forbidden City",
    "Notre-Dame de Paris",
    "Chichén Itzá",
    "Stonehenge",
    "Santorini",
    "Prague Castle",
    "Dubrovnik city walls",
    "Wat Arun",
    "Basilica di Santa Maria del Fiore",
    "Hohensalzburg Fortress",
    "Belem Tower",
    "Topkapi Palace",
    "Château de Chambord",
    "Table Mountain",
    "Plitvice Lakes",
    "Cinque Terre",
    "Meiji Shrine",
    "Schönbrunn Palace",
    "Plaza de España (Seville)",
    "Buda Castle",
    "St. Basil's Cathedral",
    "Hassan II Mosque",
    "Potala Palace",
  ],
  3: [
    "Bagan",
    "Meteora",
    "Moai",
    "Göbekli Tepe",
    "Sigiriya",
    "Borobudur",
    "Lalibela",
    "Persepolis",
    "Great Zimbabwe",
    "Hampi",
    "Tikal",
    "Newgrange",
    "Mont-Saint-Michel",
    "Ajanta Caves",
    "Cappadocia",
    "Socotra",
    "Zhangjiajie",
    "Skellig Michael",
    "Jeju Island",
    "Banaue Rice Terraces",
    "Ellora Caves",
    "Prambanan",
    "Itchan Kala",
    "Tugela Falls",
    "Lake Bled",
    "Hallstatt",
    "Jiuzhaigou",
    "Trolltunga",
    "Giant's Causeway",
    "Salar de Uyuni",
  ],
};
