project_id = "jrpwlvdwhuxpbqykomzw"

[functions.mapillary-search]
verify_jwt = false
[functions.youtube-playlist]
verify_jwt = false
[functions.ingest-news]
verify_jwt = false
[functions.auto-reset-round]
verify_jwt = false
[functions.generate-thisorthat]
verify_jwt = false
[functions.youtube-search]
verify_jwt = false
